spring:
  datasource:
    url: jdbc:h2:mem:testThread
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      file-size-threshold: 100KB # define this to allow more than 2 files to be uploaded when executing the apis